#!/usr/bin/env bash
#Description: changes the IP address of your local computer

cp /etc/hosts ~/hosts.n
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.n
sed -i "/.*facebook.com/c\8.8.8.8 facebook.com" ~/hosts.n
cp -f ~/hosts.n /etc/hosts
rm ~/hosts.n
